env:
  dataset: /tmp2/edwardlee/food-11
  checkpoint: /tmp2/edwardlee/food-11-ckpt
  k-max-ckpt: 5
epochs: 1024
optimizer:
  name: RAdam
  kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-4
batch-size: 128
mixup:
  enable: true
  alpha: 0.4
test-time-augmentation:
  weight: 0.2
  candidates: 5
seed: 6666
scheduler:
  name: StepLR
  kwargs:
    gamma: 0.1
    step_size: 1024
    step_unit: epoch
early-stop: 1024
model:
  resize: [224, 224]
