env:
  dataset: /tmp2/edwardlee/food-11
  checkpoint: /tmp2/edwardlee/food-11-ckpt
  k-max-ckpt: 5
epochs: 768
optimizer:
  name: RAdam
  kwargs:
    lr: 1.0e-4
    weight_decay: 1.0e-4
scheduler:
  name: StepLR
  kwargs:
    gamma: 0.1
    step_size: 512
    step_unit: epoch
batch-size: 64
mixup:
  enable: true
  alpha: 0.4
test-time-augmentation:
  weight: 0.2
  candidates: 11
seed: 3407
early-stop: 1024
model:
  input-size:
    train:
      height: 224
      width: 224
    test:
      height: 224
      width: 224
