env:
  dataset: /tmp2/edwardlee/dataset/voxceleb2
  checkpoint: /tmp2/edwardlee/checkpoints/voxceleb2
optimizer:
  name: AdamW
  kwargs:
    lr: 1.0e-3
    weight_decay: 0
batch-size: 1024
seed: 48763
ratio: 0.9
segment_len: 128
model:
  d_model: 80
  dim_feedforward: 1024
  n_head: 4
  normalize: true
