env:
  dataset: /tmp2/edwardlee/dataset/anomaly
  checkpoint: /tmp2/edwardlee/checkpoints/anomaly
iterations: 80000
optimizer:
  name: Adam
  kwargs:
    lr: 5.0e-4
    weight_decay: 0
scheduler:
  name: StepLR
  kwargs:
    step_size: 4000
    gamma: 0.95
batch-size:
  train: 256
  test: 256
seed: 0
model:
  type: fcn
