#!/bin/bash

# Clean up previous generated results
if [[ -d results ]]; then
    echo "Clean directory result";
    rm -r results;
fi

stylegan2_pytorch --data ../../../dataset/crypko/faces \
    --generate \
    --num-image-tiles 1 \
    --num-generate 1000

# Pack all images generated by EMA model.
cd results/default;
tar -zcvf ../../submission.tgz *-ema.jpg;
cd ../../;

