env:
  dataset: ../../../dataset/crypko
  checkpoint: ../../../dataset/crypko
optimizer:
  name: AdamW
  kwargs:
    lr: 1.0e-3
    weight_decay: 0
batch-size: 1024
seed: 4096
ratio: 0.9
segment_len: 128
model:
  d_model: 80
  dim_feedforward: 1024
  n_head: 4
  normalize: true
